### ISSUE TITLE
Reduce build time in circleci

### ISSUE THREAD

**Issue by Lbird** [amolabs/amoabci#142]
Consider build goleveldb version only in circleci.
In that case, build additional cleveldb version when deploying.

**Comment by h0n9** [comment]
this issue is resolved in:
https://github.com/amolabs/amoabci/commit/2c1718736e95fa4b29c326dec869c512a4a458f0
https://github.com/amolabs/amoabci/commit/20cf2d6b9917564898b5b456fe3fb0f41102d970
