### ISSUE TITLE
Countermeasure against replay attack

### ISSUE THREAD

**Issue by Lbird** [amolabs/amoabci#152]
to implement:
- record txs included in blocks
- ignore(or remove) too old tx
- in checkTx(), check if tx is already included in block

to consider:
- how to bind tx to block height
- how to prevent malicious users abusing binding txs

**Comment by Lbird** [comment]
This is necessary due to the tendermint issue tendermint/tendermint#3865. The issue harms overall performance.

**Comment by h0n9** [comment]
https://docs.tendermint.com/app-dev/app-development.html#replay-protection could be helpful
