### ISSUE TITLE
Remove nonce in transaction fields

### ISSUE THREAD

**Issue by Lbird** [amolabs/amoabci#176]
Since we have replay attack countermeasure, nonce in transaction fields is obsolete now.

**Comment by h0n9** [comment]
for amocli resolved in https://github.com/amolabs/amo-client-go/commit/bd3783616231cc9a9e1464051eb5a27cdc52798f

**Comment by h0n9** [comment]
for docs resolved in https://github.com/amolabs/docs/commit/8c05dae3747ded6c5c23d2eb7b6df96742ad85d6
