### ISSUE TITLE
Replace history records with TM events (tags)

### ISSUE THREAD

**Issue by Lbird** [amolabs/amoabci#251]
Add the following events:
- [x] begin block events
  - [x] protocol change
  - [ ] ~~(check) evidence?~~
- [x] end block events
  - [x] draft status change
  - [x] config change
  - [x] stake unlock
  - [x] balance change without explicit tx
    - [x] incentive
    - [x] penalty
    - [x] disposition of draft deposit
- [x] tx events
  - [x] draft proposal with mediated config

Remove the following DBs and their relative functions:
- [x] incentiveDB
  - [x] incentiveHeight
  - [x] incentiveAddress
  - [x] penaltyHeight
  - [x] penaltyAddress

Remove the following descriptions:
- [x] History Record (https://github.com/amolabs/docs/blob/master/protocol.md#history-record)

Remove the following functions:
- [x] amo-client-go (https://github.com/amolabs/amo-client-go)
  - [x] query
    - [x] incentive
    - [x] penalty
- [ ] amo-client-js (https://github.com/amolabs/amo-client-js)
  - [ ] queryIncBlock(height)
  - [ ] queryIncAddress(address)
  - [ ] queryInc(height, address)

**Comment by h0n9** [comment]
Following events are not applied yet for its uncertain uses:
- begin block events
  - (check) evidence?
- end block event
  - balance change without explicit tx
    - disposition of draft deposit
